/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoomManagerRouteImport } from './routes/room-manager'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'
import { Route as BookingShowtimeIdRouteImport } from './routes/booking.$showtimeId'
import { Route as BookingSuccessBookingIdRouteImport } from './routes/booking-success.$bookingId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomManagerRoute = RoomManagerRouteImport.update({
  id: '/room-manager',
  path: '/room-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingShowtimeIdRoute = BookingShowtimeIdRouteImport.update({
  id: '/booking/$showtimeId',
  path: '/booking/$showtimeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessBookingIdRoute = BookingSuccessBookingIdRouteImport.update({
  id: '/booking-success/$bookingId',
  path: '/booking-success/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tickets': typeof MyTicketsRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/room-manager': typeof RoomManagerRoute
  '/search': typeof SearchRoute
  '/booking-success/$bookingId': typeof BookingSuccessBookingIdRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tickets': typeof MyTicketsRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/room-manager': typeof RoomManagerRoute
  '/search': typeof SearchRoute
  '/booking-success/$bookingId': typeof BookingSuccessBookingIdRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-tickets': typeof MyTicketsRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/room-manager': typeof RoomManagerRoute
  '/search': typeof SearchRoute
  '/booking-success/$bookingId': typeof BookingSuccessBookingIdRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manager'
    | '/my-tickets'
    | '/payment'
    | '/register'
    | '/room-manager'
    | '/search'
    | '/booking-success/$bookingId'
    | '/booking/$showtimeId'
    | '/movies/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manager'
    | '/my-tickets'
    | '/payment'
    | '/register'
    | '/room-manager'
    | '/search'
    | '/booking-success/$bookingId'
    | '/booking/$showtimeId'
    | '/movies/$movieId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/manager'
    | '/my-tickets'
    | '/payment'
    | '/register'
    | '/room-manager'
    | '/search'
    | '/booking-success/$bookingId'
    | '/booking/$showtimeId'
    | '/movies/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  MyTicketsRoute: typeof MyTicketsRoute
  PaymentRoute: typeof PaymentRoute
  RegisterRoute: typeof RegisterRoute
  RoomManagerRoute: typeof RoomManagerRoute
  SearchRoute: typeof SearchRoute
  BookingSuccessBookingIdRoute: typeof BookingSuccessBookingIdRoute
  BookingShowtimeIdRoute: typeof BookingShowtimeIdRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-manager': {
      id: '/room-manager'
      path: '/room-manager'
      fullPath: '/room-manager'
      preLoaderRoute: typeof RoomManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$showtimeId': {
      id: '/booking/$showtimeId'
      path: '/booking/$showtimeId'
      fullPath: '/booking/$showtimeId'
      preLoaderRoute: typeof BookingShowtimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success/$bookingId': {
      id: '/booking-success/$bookingId'
      path: '/booking-success/$bookingId'
      fullPath: '/booking-success/$bookingId'
      preLoaderRoute: typeof BookingSuccessBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  MyTicketsRoute: MyTicketsRoute,
  PaymentRoute: PaymentRoute,
  RegisterRoute: RegisterRoute,
  RoomManagerRoute: RoomManagerRoute,
  SearchRoute: SearchRoute,
  BookingSuccessBookingIdRoute: BookingSuccessBookingIdRoute,
  BookingShowtimeIdRoute: BookingShowtimeIdRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
